# Generated by Django 2.1.2 on 2018-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_numb', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
