# Generated by Django 2.1.2 on 2018-10-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small_admin_app', '0002_arcmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user_computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='small_admin_app.Computers')),
            ],
        ),
    ]
