# Generated by Django 2.1.2 on 2018-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_admin_app', '0004_user_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_computer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
