# Generated by Django 2.1.2 on 2018-10-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small_admin_app', '0005_auto_20181005_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('division_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='small_admin_app.Divisions')),
                ('user_computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='small_admin_app.Computers')),
            ],
        ),
    ]
