# Generated by Django 2.1.2 on 2018-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_admin_app', '0007_divisions_division_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='divisions',
            name='division_number',
        ),
    ]
