# Generated by Django 2.1.2 on 2018-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_admin_app', '0008_auto_20181005_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='name',
            field=models.CharField(default='DESIGN', max_length=36),
            preserve_default=False,
        ),
    ]
